project:
  type: website
  output-dir: docs


website:
  title: "Communicating With Data"
  twitter-card: 
    creator: "@PieRatio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/robertwwalker/CommunicatingWithData
      - icon: twitter
        href: https://twitter.com/PieRatio
format:
  html:
    theme: 
      light: flatly
      dark: vapor
    css: styles.css
    toc: true
    html-math-method: katex
